# Reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
name: "🐞 Bug report"
description: File a bug report.
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to report an issue!
      Please make sure to follow the instructions.
      This helps us to quickly understand and reproduce your problem.

- type: textarea
  attributes:
    label: Bug description
    value: |
      <!--- Provide a general summary of the issue in the title above -->

      ## Steps to reproduce
      <!--- 
        Provide short and simple instructions to reproduce your problem.
        Include code snippets or a link to a public repository, if relevant
      -->
      1.
      2.
      3.

      ## Expected behavior
      <!--- Tell us what should happen -->

      ## Current behavior
      <!--- Tell us what happens instead of the expected behavior -->

      ## Environment
      <!--- Relevant information like your operating system, browser, package versions etc. -->

      ## Detailed information
      <!--- Optional, if you have more detailed information, or if you know a possible solution. -->
  validations:
    required: true

- type: textarea
  attributes:
    label: Logs
    value: |
      <!-- 
        Use this field if you have detailed log messages that can help us diagnose the issue.
        Otherwise, simply remove this text.
      -->

      <details>
      <summary>Expand</summary>
      
      ```text
      # Put your content here
      ```
      </details>

- type: checkboxes
  attributes:
    label: Validations
    description: Please make sure that you follow these steps before submitting the issue
    options:
      - label: Read and follow our [code of conduct](https://github.com/open-pioneer/.github/blob/main/CODE_OF_CONDUCT.md)
        required: true
      - label: Read the [contributing guidelines](https://github.com/open-pioneer/trails-starter/blob/main/docs/Contributing.md)
        required: true
      - label: Check that there isn't already a similar issue
        required: true
